# Generated by Django 3.0.2 on 2020-01-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(choices=[('Real Estate Brooker', 'Real Estate Brooker'), ('Buying Agent', 'Buying Agent'), ('Selling Agent', 'SA'), ('Other', 'O')], max_length=20)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='agent/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('description', models.TextField()),
                ('username', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
