# Generated by Django 3.0.2 on 2020-01-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='agent/'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='title',
            field=models.CharField(choices=[('Real Estate Brooker', 'REB'), ('Buying Agent', 'BA'), ('Selling Agent', 'SA'), ('Other', 'O')], max_length=20),
        ),
    ]
