# Generated by Django 3.0.2 on 2020-01-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_auto_20200107_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F')], default='M', max_length=6),
            preserve_default=False,
        ),
    ]
