# Generated by Django 3.0.2 on 2020-01-07 19:35

from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governorate_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='governorate/')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='property/')),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('sale', 'S'), ('rent', 'R')], max_length=4)),
                ('installment', models.BooleanField(default=True)),
                ('beds_room_number', models.PositiveIntegerField()),
                ('baths_number', models.PositiveIntegerField()),
                ('garages_number', models.PositiveIntegerField()),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Governorate')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
