# Generated by Django 3.0.2 on 2020-01-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(default='blaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='garages_number',
            field=models.PositiveIntegerField(),
        ),
    ]
