# Generated by Django 3.0.2 on 2020-01-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_governorate_the_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governorate',
            name='the_property',
        ),
        migrations.AddField(
            model_name='governorate',
            name='the_property',
            field=models.ManyToManyField(related_name='governorate_property', to='properties.Property'),
        ),
    ]
