# Generated by Django 3.0.2 on 2020-01-07 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20200107_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='governorate',
            name='the_property',
        ),
    ]
