# Generated by Django 3.0.2 on 2020-01-09 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_reserveproperty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserveproperty',
            options={'verbose_name': 'Reserve Property', 'verbose_name_plural': 'Reserve Properties'},
        ),
    ]
